### ISSUE TITLE
open blockexplorer by clicking on a transaction

### ISSUE THREAD

**Issue by karamble** [decred/Paymetheus#279] opened 2017-05-18 22:15 UTC
Users approached me and they wish to be able to open the blockexplorer by clicking on a transaction and they claim to be unable to mark copy+paste the txid

**Comment by jrick** [comment] 2017-05-19 14:46
I'd rather just make copy work, it is a more general solution and it should be possible to copy the hash without opening the block explorer.  It is already implemented in the overview (right click -> copy transaction hash) but needs to implemented in other places (like the history pane).

**Comment by jrick** [comment] 2017-05-19 14:47
Also, duplicate of #236

**Closed as completed by jrick** 2017-05-19 14:47 UTC
Labels: duplicate
