### ISSUE TITLE
Closing Paymetheus doesn't close the background instance of DCRD 

### ISSUE THREAD

**Issue by David00** [decred/Paymetheus#237] opened 2017-04-11 18:18 UTC
This prevents the full version of Paymetheus ("Decred") from starting up properly next time, throwing an error: "Consensus server exited with code 1"

dcrd.exe has to be manually stopped in task viewer for Decred to successfully launch again.

Windows 7 64 bit
Paymetheus version: decred_0.8.2-beta_x64.msi

**Comment by jrick** [comment] 2017-04-11 18:23
We've definitely tested this so I'm unsure why it is not working for you.  Can you grab the end of the dcrd logs (in `%localappdata%/dcrd/logs/mainnet/dcrd.log`)?

**Comment by David00** [comment] 2017-04-11 18:31
Sure, the log is attached.

My case isn't really the normal end user case, so maybe I uncovered something not specifically tested for. I had only fired up Paymetheus to try helping a forum user.  Normally I use the CLI versions so my AppData/Local had existing data from my dcrd.exe instance.  Also, I didn't create a wallet in Paymetheus, so that could be it too.  I am closing Paymetheus (the "Decred" version) from the "Create a new wallet" and "Restore a wallet from seed" screen.

[dcrd[4-11].txt](https://github.com/decred/Paymetheus/files/914326/dcrd.4-11.txt)

**Comment by jrick** [comment] 2017-04-26 15:28
If you can reproduce this without any other dcrd running then feel free to reopen, but I'm going to close this now since running both the Decred shortcut and your own node separately isn't supported (this is what the standalone version is for).  From those logs it appears that there are multiple dcrd instances that were writing to the log file all at the same time.

**Closed as completed by jrick** 2017-04-26 15:28 UTC
