### ISSUE TITLE
Validate 0.6.0 release

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#188] opened 2016-11-08 13:46 UTC
Validate paymetheus on x86 and x64:
- [x] Windows 7 x64
- [ ] Windows 7 x86
- [x] Windows 10 x64
- [ ] Windows 10 x86

Make sure both icons launch paymetheus correctly.
Ensure that that we can copy the key to clipboard and that we can't paste it when asked for.

In the comments note which OS you tested and the results.

**Comment by jcvernaleo** [comment] 2016-11-09 14:22
64bit win7 looks good for new and upgrade.

**Comment by jcvernaleo** [comment] 2016-11-09 19:39
retested win7, still good.

**Comment by jrick** [comment] 2016-11-09 19:51
After the latest rounds of fixes, not seeing any regressions over the 0.5.0 release.  Tested win10/amd64

**Comment by jolan** [comment] 2016-11-09 20:05
Re-tested 64 bit Windows 10 and no unexpected issues.

**Comment by jcvernaleo** [comment] 2016-11-10 15:16
Testing was finished and release is out so I'm closing this.
The x86 tests cannot be done since none of us have 32 bit windows.  It really should not be listed in our test matrix anymore.

**Closed as completed by jcvernaleo** 2016-11-10 15:16 UTC
