### ISSUE TITLE
Crashes with BlockChainConsistencyException whenever dcrwallet processes a reorg

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#59] opened 2016-07-01 16:38 UTC
<img width="360" alt="exception_during_ibd" src="https://cloud.githubusercontent.com/assets/4366787/16528102/50603c52-3f80-11e6-813a-46cf3235ec60.PNG">

**Comment by marcopeereboom** [comment] 2016-07-01 16:44
Left over wallet bits.  Can be fixed in next release.

**Comment by jrick** [comment] 2016-07-01 16:45
This is probably due to an old wallet in the Paymetheus app data dir which is synced ahead of a new dcrd instance in IBD.

**Comment by marcopeereboom** [comment] 2016-07-25 16:34
PEBCAK

**Comment by jrick** [comment] 2016-07-26 14:10
I think this is still an issue.  Paymetheus appears to break whenever wallet processes a reorg.

**Comment by jrick** [comment] 2016-07-26 14:29
For example, I just saw this happen again:

![image](https://cloud.githubusercontent.com/assets/1420313/17141831/b858aee4-531b-11e6-889c-e5d3195c2c63.png)

This occurred after both dcrwallet and paymetheus had synchronized (to dcrd and dcrwallet respectively), and after sending a couple transactions.  It's not a problem just with processing reorgs that happened when dcrwallet was not running.

Will add unit tests for handling reorgs.

**Comment by jrick** [comment] 2016-07-27 18:53
This must have been due to the lack of votes on testnet yesterday.  No longer seeing these crashes during wallet reorgs.

**Comment by jrick** [comment] 2016-08-04 19:02
Some reorgs still invoke this bug while others don't.  Unsure why.

![image](https://cloud.githubusercontent.com/assets/1420313/17414698/696cd9aa-5a54-11e6-9576-e8bd9ef3f1e5.png)

**Comment by jrick** [comment] 2016-11-21 23:25
This might be fixed after some fixes that have already hit wallet (in gRPC server API version 3.0.1).  I'll investigate this more tomorrow and see if we can close this, or if there is more work to be done.

**Comment by jrick** [comment] 2016-11-22 20:32
So there are two issues, the first one, which marco reported, happened when wallet was started with a new (or no) dcrd database and wallet internally performed a giant reorg, which was then notified to Paymetheus.  #185 is a duplicate of this bug.  The second was a reorg that wallet notified while it was up to date due to bugs in older versions of the gRPC server API, and fixed in version 3.0.1.

I'll close this issue, since the bug I was experiencing is now fixed, and leave #185 open as it describes the original error in more detail.

**Closed as completed by jrick** 2016-11-22 20:32 UTC
Labels: bug
