### ISSUE TITLE
Whether or not the wallet has a public passphrase should be stored in the .ini file

### ISSUE THREAD

**Issue by cjepson** [decred/Paymetheus#95] opened 2016-07-12 22:19 UTC
If the user does not elect to use a public passphrase, the ini file should store this information and bypass the public passphrase screen in the future.

**Comment by jrick** [comment] 2016-07-12 22:31
duplicate of #48

And it's not a given that it will be saved in the ini configuration.  Ideally this information is saved by the wallet itself and is made available to all clients.

**Closed as completed by jrick** 2016-07-12 22:31 UTC
Labels: UX
