### ISSUE TITLE
Spendable visual bug, After tickets have voted, should be unspendable for 256 blocks

### ISSUE THREAD

**Issue by jiecut42** [decred/Paymetheus#272] opened 2017-05-12 04:14 UTC
> After a ticket has voted, missed, or expired, the funds (ticket price and subsidy if applicable, minus the fee) will enter immature status for another 256 blocks, after which they are released. If a ticket is missed or expired, a ticket revocation transaction is submitted by the wallet which then frees up the locked ticket outputs. NOTE: Revocations can only be submitted for a corresponding missed ticket. You cannot revoke a ticket until it is missed.

After a ticket has voted it is unspendable for 256 blocks.

So the bug is that in my default account I have 68 DCR and it says 68 DCR is spendable. But 47 DCR of that is actually locked because of the immature status.  That's why when I try to send 25+ DCR in a transaction the send button will be grayed out, and when I try to purchase a ticket it'll say that funds couldn't be secured.

So part of the client knows that those funds are locked, but the visual part in accounts shows that it's currently spendable.

**Comment by jrick** [comment] 2017-05-12 12:59
Duplicate of #225

**Closed as completed by jrick** 2017-05-12 12:59 UTC
Labels: duplicate
