### ISSUE TITLE
Validate v1.0.5

### ISSUE THREAD

**Issue by jcvernaleo** [decred/Paymetheus#301] opened 2017-06-20 21:25 UTC
- [x] Win7
- [x] Win10

**Comment by jrick** [comment] 2017-06-20 22:06
Upgrade went fine but i am investigating why a fresh reseed and without a dcrd previously synced is showing errors.

Don't know if these issues are new or not yet.

**Comment by jolan** [comment] 2017-06-21 13:54
Win 10 64-bit upgrade went OK.

Clean install is syncing fine so far.

**Comment by jcvernaleo** [comment] 2017-06-21 14:18
win7 seemed fine in both cases for me.  It is on a slow VM so I can't test much as usual, but no obvious regressions from last time.

**Comment by jrick** [comment] 2017-06-21 14:20
No issues noted during upgrade on win10.

Did some additional testing this round when reseeding and without a previously synced chain, and i was noticing errors there (the error message said "credit value missing", and looking through the dcrwallet code i wasn't entirely sure what could have been causing this), but in any case i don't believe these are new regressions.  If others can't reproduce let's roll with this release and I will debug this in my environment later.

**Comment by jrick** [comment] 2017-06-21 14:37
Closing this, reopen if more issues are discovered or anyone else can hit the missing credit error on seed restore without doing a full IBD.

**Closed as completed by jrick** 2017-06-21 14:37 UTC
Labels: help wanted
