### ISSUE TITLE
error thrown when dcrd changes databases

### ISSUE THREAD

**Issue by jolan** [decred/Paymetheus#185] opened 2016-10-07 15:07 UTC
This came up:

![wallet error](https://i.imgur.com/f0b9qYt.png)

while doing release testing:

decred/decred-windows-installer#17

**Comment by jrick** [comment] 2016-10-07 15:13
I don't think any kind of manual fiddling of the appdata files can prevent this.  The only workaround I see is starting (only) dcrd manually and letting it resync the entire blockchain before opening Paymetheus.  Fixing Paymetheus' code in this case is non-trivial as it was not designed for huge reorgs (which is what happens to the wallet when it connects to a way behind dcrd).

**Comment by jolan** [comment] 2016-10-07 15:23
I figured that was the case. I agree that it's not worth the work to fix it given that this will hopefully be the only time it comes up.

**Comment by jrick** [comment] 2016-11-22 20:27
This looks like a duplicate of #59, at least it looks the same as marco's error message in the first post.

**Comment by jrick** [comment] 2016-11-22 20:34
I plan on fixing this with all the changes being made to the startup process for the new activity views.

**Comment by jrick** [comment] 2016-12-16 18:36
This error is fixed.  Instead we've traded bugs for https://github.com/decred/Paymetheus/issues/207.

**Closed as completed by jrick** 2016-12-16 18:36 UTC
Labels: bug
